deploymentMode: aio
hoppscotch:
  frontend:
    enableSubpathBasedAccess: false
aio:
  readinessProbe:
    initialDelaySeconds: 15
postgresql:
  enabled: true
  auth:
    username: hoppscotch
    password: hoppscotch
    database: hoppscotch
  primary:
    persistence:
      enabled: false
