deploymentMode: distributed
hoppscotch:
  backend:
    enterpriseLicenseKey: your-enterprise-license-key
frontend:
  image:
    repository: hoppscotch/hoppscotch-frontend-enterprise
  ingress:
    enabled: true
    hostname: frontend.hoppscotch.local
    tls: true
    selfSigned: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
backend:
  readinessProbe:
    initialDelaySeconds: 15
  image:
    repository: hoppscotch/hoppscotch-backend-enterprise
  ingress:
    enabled: true
    hostname: backend.hoppscotch.local
    tls: true
    selfSigned: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
admin:
  image:
    repository: hoppscotch/hoppscotch-admin-enterprise
  ingress:
    enabled: true
    hostname: admin.hoppscotch.local
    tls: true
    selfSigned: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
postgresql:
  enabled: true
  auth:
    username: hoppscotch
    password: hoppscotch
    database: hoppscotch
  primary:
    persistence:
      enabled: false
