deploymentMode: distributed
frontend:
  ingress:
    enabled: true
    hostname: frontend.hoppscotch.local
    tls: true
    selfSigned: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
backend:
  readinessProbe:
    initialDelaySeconds: 15
  ingress:
    enabled: true
    hostname: backend.hoppscotch.local
    tls: true
    selfSigned: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
admin:
  ingress:
    enabled: true
    hostname: admin.hoppscotch.local
    tls: true
    selfSigned: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
postgresql:
  enabled: true
  auth:
    username: hoppscotch
    password: hoppscotch
    database: hoppscotch
  primary:
    persistence:
      enabled: false
