{{- if and .Values.proxyscotch.enabled .Values.proxyscotch.metrics.enabled .Values.proxyscotch.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "hoppscotch.proxyscotch.name" . }}
  namespace: {{ default (include "hoppscotch.namespace" .) .Values.proxyscotch.metrics.serviceMonitor.namespace | quote }}
  labels:
    app.kubernetes.io/component: {{ include "hoppscotch.proxyscotch.component" . }}
    {{- include "hoppscotch.labels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- toYaml .Values.commonAnnotations | nindent 4 }}
  {{- end }}
spec:
  jobLabel: {{ .Values.proxyscotch.metrics.serviceMonitor.jobLabel | quote }}
  selector:
    matchLabels:
      app.kubernetes.io/component: {{ include "hoppscotch.proxyscotch.component" . }}
      {{- include "hoppscotch.selectorLabels" . | nindent 6 }}
      {{- if .Values.proxyscotch.metrics.serviceMonitor.selector }}
      {{- toYaml .Values.proxyscotch.metrics.serviceMonitor.selector | nindent 6 }}
      {{- end }}
  endpoints:
    - port: metrics
      path: /metrics
      {{- if .Values.proxyscotch.metrics.serviceMonitor.tlsConfig }}
      scheme: https
      tlsConfig:
        {{- toYaml .Values.proxyscotch.metrics.serviceMonitor.tlsConfig | nindent 8 }}
      {{- end }}
      {{- if .Values.proxyscotch.metrics.serviceMonitor.interval }}
      interval: {{ .Values.proxyscotch.metrics.serviceMonitor.interval }}
      {{- end }}
      {{- if .Values.proxyscotch.metrics.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ .Values.proxyscotch.metrics.serviceMonitor.scrapeTimeout }}
      {{- end }}
      {{- if .Values.proxyscotch.metrics.serviceMonitor.honorLabels }}
      honorLabels: {{ .Values.proxyscotch.metrics.serviceMonitor.honorLabels }}
      {{- end }}
      {{- if .Values.proxyscotch.metrics.serviceMonitor.metricsRelabelings }}
      metricRelabelings:
        {{- toYaml .Values.proxyscotch.metrics.serviceMonitor.metricsRelabelings | nindent 8 }}
      {{- end }}
      {{- if .Values.proxyscotch.metrics.serviceMonitor.relabelings }}
      relabelings:
        {{- toYaml .Values.proxyscotch.metrics.serviceMonitor.relabelings | nindent 8 }}
      {{- end }}
  namespaceSelector:
    matchNames:
      - {{ include "hoppscotch.namespace" . | quote }}
{{- end }}
